/* Example of Outcome used with C APIs
(C) 2017-2018 Niall Douglas <http://www.nedproductions.biz/> (149 commits)


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

//! [program]
#include <stdio.h>
#include <string.h>  // for strerror
// This header in Outcome is pure C, it provides a suite of C helper macros
#include "../../../include/outcome/result.h"

// Declare our C++ function's returning result type. Only needs to be done once.
CXX_DECLARE_RESULT_EC(size_t, size_t);

// Tell C about our C++ function
extern CXX_RESULT_EC(size_t) to_string(char *buffer, size_t bufferlen, int v);

void print(int v)
{
  char buffer[4];
  CXX_RESULT_EC(size_t) res;

  res = to_string(buffer, sizeof(buffer), v);
  if(CXX_RESULT_HAS_VALUE(res))
  {
    printf("to_string(%d) fills buffer with '%s' of %zu characters\n", v, buffer, res.value);
    return;
  }
  // Is the error returned in the std::generic_category domain and thus an errno?
  if(CXX_RESULT_ERROR_IS_ERRNO(res))
  {
    // If you get a weird compile error here, note that CXX_RESULT_ERROR()
    // uses C11 generics, you need a C11 compiler for it to work. If you don't
    // have a C11 compiler, res.error or res.error.code can be used directly.
    fprintf(stderr, "to_string(%d) failed with error code %d (%s)\n", v, CXX_RESULT_ERROR(res), strerror(CXX_RESULT_ERROR(res)));
    return;
  }
  fprintf(stderr, "to_string(%d) failed with unknown error code %d\n", v, CXX_RESULT_ERROR(res));
}

int main(void)
{
  print(9);
  print(99);
  print(999);
  print(9999);
  return 0;
}
