name: Unit tests Linux

on:
  push:
    branches:
    - develop
    - master
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  Linux:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang++-19, g++, libc++]
    env:
      NAME: Linux-${{ matrix.compiler }}
      CXX: ${{ matrix.compiler }}
          
    steps:
    - uses: actions/checkout@v4
    
    - name: CMake tests Linux
      shell: bash
      run: |
       if [ "${{ matrix.compiler }}" = "libc++" ]; then
         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -;
         sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main";
         sudo apt update;
         sudo apt install clang-19 libc++-19-dev libc++abi-19-dev libomp-19-dev;
         export CMAKE_CONFIGURE_OPTIONS="-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-linux-libc++.cmake";
         ctest -S .ci.cmake -VV -E noexcept --timeout 900 "-DCTEST_CONFIGURE_OPTIONS=$CMAKE_CONFIGURE_OPTIONS";
       elif [ "${{ matrix.compiler }}" = "clang++-19" ]; then
         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -;
         sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main";
         sudo apt update;
         sudo apt install clang-19 libc++-19-dev libc++abi-19-dev libomp-19-dev;
         ctest -S .ci.cmake -VV --timeout 900 "-DCTEST_CONFIGURE_OPTIONS=$CMAKE_CONFIGURE_OPTIONS";
       else
         ctest -S .ci.cmake -VV --timeout 900 "-DCTEST_CONFIGURE_OPTIONS=$CMAKE_CONFIGURE_OPTIONS";
       fi
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Linux ${{ matrix.compiler }} test results
        path: prebuilt/merged_junit_results.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: [Linux]
    runs-on: ubuntu-latest
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '**/merged_junit_results.xml'
